language: java

dist: trusty

jdk:
  - oraclejdk8

env:
  - DISPLAY=: 99.0 

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: francescoterrosi-github
    token:
      secure: "NorcnpKheVRMEtbuBhgQfAMboj21UP4U9l8vAQ5QHdpwxudboNvDg6yWw5bPyiryZA0HlaU8rGqi+vDNMIhD7hrGYi6JcuWhO6k35p/j1UrKa6A8A7DSghtdN63el2+rGpRnia9KnDIpA4YHQ38QAvKiTgG22O5jsyb1/UZYb2dMUIF6yCeHAfCbg3iXfxemQT4HWPSBQuCIEh+OhU2VUfh/QdcB4MRD4Bfe+vjPxgs/RXPB8I9lHP9BYTBkQAOc/Wcf9hSKuV1t/f+Dj1lJsNXTXks0JtjZ4nDcP4t0TndrSsJqfL487RtVz+RZXgKNU2S8wXCpBptPx4gELmPq/T8i6eXpv/68KTng1g7dlH1aD19vrZsP8acYGmwhms89PrVVuN6b7MYpf7tqgoVvr7ToJm3w43OEl874Tf+/g6djwVlvXobsJIKTrEqjYAQfK9mksqW6TuE4y6DQYIGGUtH1ZAAKKBvTJ/BOOci7v9ncbWIoQOYTkUcL/6TeMKKUO/6/tGBvHkensrcIq3Z9edb1ip1Q3ioY86HXd7FkMY3ayUe95h0hr4Q9tzIBv7nzZ/mI56RpeYsW2p+WURzlD8qUUmd9ysV6H0zeC3weuTuI/8vtvM57ZxA6Ybdfi/PC4UaKV0QNZVMfHb0Ea/f7Jfld9WFRoF9qGEKGa89PF0o="

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3
  - cd ./rehearsal-room-gradle

script:
  - ./gradlew build jacocoTestReport coveralls sonarqube
